version: '3.4'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - '80:80'     # Public HTTP Port
      - '443:443'   # Public HTTPS Port
      - '81:81'     # Admin Web UI
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - './shared/nginx-proxy-manager/data:/data'
      - './shared/nginx-proxy-manager/letsencrypt:/etc/letsencrypt'
    networks:
      proxy:
        aliases:
          - sts.vhcastro.local
          - admin.vhcastro.local
          - admin-api.vhcastro.local
    restart: always

  identityserver.admin:
    image: '${DOCKER_REGISTRY-}vhcastro-duende-identityserver-admin'
    build:
      context: .
      dockerfile: src/IdentityServer.Admin/Dockerfile
    container_name: vhcastro-duende-identityserver-admin
    environment:
      - VIRTUAL_HOST=admin.vhcastro.local
      - 'ConnectionStrings__ConfigurationDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__IdentityDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__AdminLogDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.vhcastro.local'
      - 'AdminConfiguration__IdentityAdminRedirectUri=https://admin.vhcastro.local/signin-oidc'
      - 'AdminConfiguration__IdentityServerBaseUrl=https://sts.vhcastro.local'
      - AdminConfiguration__RequireHttpsMetadata=false
      - 'IdentityServerData__Clients__0__ClientUri=https://admin.vhcastro.local'
      - 'IdentityServerData__Clients__0__RedirectUris__0=https://admin.vhcastro.local/signin-oidc'
      - 'IdentityServerData__Clients__0__FrontChannelLogoutUri=https://admin.vhcastro.local/signin-oidc'
      - 'IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://admin.vhcastro.local/signout-callback-oidc'
      - 'IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://admin.vhcastro.local'
      - 'IdentityServerData__Clients__1__RedirectUris__0=https://admin-api.vhcastro.local/swagger/oauth2-redirect.html'
      - 'Serilog__WriteTo__1__Args__connectionString=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    command: bash -c "cp /usr/local/share/ca-certificates/rootCA.crt /etc/ssl/certs && update-ca-certificates && dotnet IdentityServer.Admin.dll /seed"
    depends_on:
      - db
      - identityserver.sts.identity
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/identitydata.json:/app/identitydata.json'
      - './shared/identityserverdata.json:/app/identityserverdata.json'
      - '${ROOT_CA_CERT_PATH}:/usr/local/share/ca-certificates/rootCA.crt'
    networks:
      proxy: null
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  identityserver.admin.api:
    image: '${DOCKER_REGISTRY-}vhcastro-duende-identityserver-admin-api'
    build:
      context: .
      dockerfile: src/IdentityServer.Admin.Api/Dockerfile
    container_name: vhcastro-duende-identityserver-admin-api
    environment:
      - VIRTUAL_HOST=admin-api.vhcastro.local
      - AdminApiConfiguration__RequireHttpsMetadata=false
      - 'AdminApiConfiguration__ApiBaseUrl=https://admin-api.vhcastro.local'
      - 'AdminApiConfiguration__IdentityServerBaseUrl=https://sts.vhcastro.local'
      - 'ConnectionStrings__ConfigurationDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__IdentityDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__AdminLogDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    command: bash -c "cp /usr/local/share/ca-certificates/rootCA.crt /etc/ssl/certs && update-ca-certificates && dotnet IdentityServer.Admin.Api.dll"
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - '${ROOT_CA_CERT_PATH}:/usr/local/share/ca-certificates/rootCA.crt'
    networks:
      proxy: null
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  identityserver.sts.identity:
    image: '${DOCKER_REGISTRY-}vhcastro-duende-identityserver-sts-identity'
    build:
      context: .
      dockerfile: src/IdentityServer.STS.Identity/Dockerfile
    container_name: vhcastro-duende-identityserver-sts-identity
    environment:
      - VIRTUAL_HOST=sts.vhcastro.local
      - 'ConnectionStrings__ConfigurationDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__IdentityDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=db;Database=IdentityServerAdmin;Username=postgres;Password=${DB_PASSWORD:-Pass123.}'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.vhcastro.local'
      - 'AdvancedConfiguration__IssuerUri=https://sts.vhcastro.local'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    command: bash -c "cp /usr/local/share/ca-certificates/rootCA.crt /etc/ssl/certs && update-ca-certificates && dotnet IdentityServer.STS.Identity.dll"
    depends_on:
      - db
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - '${ROOT_CA_CERT_PATH}:/usr/local/share/ca-certificates/rootCA.crt'
    networks:
      proxy:
        aliases:
          - sts.vhcastro.local
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: 'postgres:latest'
    ports:
      - '7900:5432'
    container_name: vhcastro-duende-identityserver-db
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD:-Pass123.}'
      POSTGRES_DB: 'IdentityServerAdmin'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    networks:
      proxy: null
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dbdata:
    driver: local

networks:
  proxy:
    driver: bridge
